version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: k8s.io/client-go
    versions:
    - 0.20.2
    - 0.20.3
  - dependency-name: k8s.io/api
    versions:
    - 0.20.2
    - 0.20.3
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.2
    - 0.20.3
  - dependency-name: k8s.io/cli-runtime
    versions:
    - 0.20.2
    - 0.20.3
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
  - dependency-name: github.com/googleapis/gnostic
    versions:
    - 0.5.3
