apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: access-matrix
spec:
  version: {{ .TagName }}
  platforms:
  - bin: access-matrix-amd64-linux
    {{ addURIAndSha "https://github.com/corneliusweig/rakkess/releases/download/{{ .TagName }}/access-matrix-amd64-linux.tar.gz" .TagName }}
    files:
      - from: LICENSE
        to: .
      - from: access-matrix-amd64-linux
        to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - bin: access-matrix-amd64-darwin
    {{ addURIAndSha "https://github.com/corneliusweig/rakkess/releases/download/{{ .TagName }}/access-matrix-amd64-darwin.tar.gz" .TagName }}
    files:
      - from: LICENSE
        to: .
      - from: access-matrix-amd64-darwin
        to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - bin: access-matrix-arm64-darwin
    {{ addURIAndSha "https://github.com/corneliusweig/rakkess/releases/download/{{ .TagName }}/access-matrix-arm64-darwin.tar.gz" .TagName }}
    files:
      - from: LICENSE
        to: .
      - from: access-matrix-arm64-darwin
        to: .
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - bin: access-matrix-amd64-windows.exe
    {{ addURIAndSha "https://github.com/corneliusweig/rakkess/releases/download/{{ .TagName }}/access-matrix-amd64-windows.zip" .TagName }}
    files:
      - from: LICENSE
        to: .
      - from: access-matrix-amd64-windows.exe
        to: .
    selector:
      matchLabels:
        os: windows
        arch: amd64
  shortDescription: Show an RBAC access matrix for server resources
  homepage: https://github.com/corneliusweig/rakkess
  caveats: |
      Usage:
        kubectl access-matrix
        kubectl access-matrix for pods
  description: |
      Show an access matrix for server resources

      This plugin retrieves the full list of server resources, checks access for
      the current user with the given verbs, and prints the result as a matrix.
      This complements the usual "kubectl auth can-i" command, which works for
      a single resource and a single verb. For example:
       $ kubectl access-matrix

      It also supports a mode which prints all subjects with access to a given
      resource (needs read access to Roles and ClusterRoles). For example:
       $ kubectl access-matrix for configmap
